version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: e-paris_nginx
  
  app:
    image: thecodingmachine/php:7.2-v1-apache-node8
    volumes:
      - ./:/var/www/html:rw
    environment:
      - VIRTUAL_HOST=app.e-paris.local
      - PHP_INI_ERROR_REPORTING=E_ALL & ~E_USER_DEPRECATED
      - PHP_EXTENSION_XDEBUG=1
    env_file:
      - .env
    container_name: e-paris_app
    links:
      - "phpmyadmin:e-paris_phpmyadmin"
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./.docker/data/mysql/:/var/lib/mysql
      - ./.docker/logs/mysql/:/var/log/mysql
    container_name: e-paris_mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      -  8080:8080
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      VIRTUAL_HOST: phpmyadmin.app.local
    container_name: e-paris_phpmyadmin

  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  
  eth:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=456719 --rpc --rpcapi "eth,net,web3" --ipcapi "eth,net,web3" --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
  
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
  
  browser-solidity:
    build: browser-solidity
    ports:
      - "8085:8085"
    container_name: Solidity_browser

  e-shop:
    image: thecodingmachine/php:7.2-v1-apache-node8
    volumes:
      - ./:/var/www/html:rw
    environment:
      - VIRTUAL_HOST=app.e-shop.local
      - PHP_INI_ERROR_REPORTING=E_ALL & ~E_USER_DEPRECATED
      - PHP_EXTENSION_XDEBUG=1
    env_file:
      - .env
    container_name: e-shop_app
    links:
      - "phpmyadmin:e-paris_phpmyadmin"
